-- moly-backend 스키마 (Supabase / PostgreSQL)
-- 단일 소스 = app/models/*.py (코드가 실제로 읽고 쓰는 형태). 설계 근거 = docs/ERD.md.
-- enum은 모델이 String 매핑(asyncpg 바인딩 마찰 회피) → DB도 text + CHECK 제약으로 검증.
-- 클라 직접 쓰기 없음(전부 서버 API 경유) → RLS deny-default(심층 방어). 서버는 owner 롤이라 RLS 우회.
-- 실행 전제: 빈 public 스키마(생성만 있음 — 기존 테이블 정리는 docs/DB_RESET_RUNBOOK.md).
-- 실행: psql "<conn>" -f db/schema.sql  (또는 python db/apply.py)

BEGIN;

-- updated_at 자동 갱신 트리거 함수(기존 존재 시 재사용). 없으면 생성.
CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ─────────────────────────────────────────────────────────────
-- 1. 계정·프로필
-- ─────────────────────────────────────────────────────────────
CREATE TABLE public.profiles (
  id                 uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  nickname           text        CHECK (char_length(nickname) <= 10),
  language           text        NOT NULL DEFAULT 'ko',
  timezone           text        NOT NULL DEFAULT 'Asia/Seoul',
  hay_balance        integer     NOT NULL DEFAULT 0 CHECK (hay_balance >= 0),
  trial_ends_at      timestamptz,
  review_prompted_at timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER profiles_set_updated_at BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ─────────────────────────────────────────────────────────────
-- 2. 서버 원본 카탈로그(FK 없음) — products / moly_life_ments / app_config
-- ─────────────────────────────────────────────────────────────
CREATE TABLE public.products (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_type         text    NOT NULL CHECK (product_type IN ('hay_pack','cosmetic')),
  name                 text    NOT NULL,
  description          text,
  -- cosmetic 전용
  public_id            text    UNIQUE,           -- API 노출용 안정 문자열 ID
  slot                 text    CHECK (slot IN ('theme','head','neck','body')),
  price_hay            integer,                 -- NULL = 구매 불가(기본 지급 등)
  is_subscriber_only   boolean NOT NULL DEFAULT false,
  asset_version        integer,
  assets               jsonb,
  -- hay_pack 전용
  hay_amount           integer,
  price_krw            integer,                 -- 표시 참고용(결제가는 StoreKit)
  app_store_product_id text    UNIQUE,
  is_active            boolean NOT NULL DEFAULT true,
  sort_order           integer NOT NULL DEFAULT 0,
  -- 타입별 컬럼 상호 강제
  CONSTRAINT products_hay_pack_ck CHECK (
    product_type <> 'hay_pack' OR (
      hay_amount IS NOT NULL AND app_store_product_id IS NOT NULL
      AND public_id IS NULL AND slot IS NULL AND price_hay IS NULL
      AND asset_version IS NULL AND assets IS NULL
      AND is_subscriber_only = false
    )
  ),
  CONSTRAINT products_cosmetic_ck CHECK (
    product_type <> 'cosmetic' OR (
      public_id IS NOT NULL AND slot IS NOT NULL
      AND hay_amount IS NULL AND app_store_product_id IS NULL AND price_krw IS NULL
      -- 구독 전용 꾸미기는 폐지 — 카탈로그에 노출되면서 구매만 막히는 상품을 만들 수 없다.
      AND is_subscriber_only = false
      -- 최종 에셋이 없는 상품은 inactive로만 준비할 수 있다.
      AND (
        is_active = false
        OR (asset_version IS NOT NULL AND asset_version >= 1 AND assets IS NOT NULL)
      )
    )
  ),
  -- user_items 복합 FK (product_id, equipped_slot) → (id, slot) 대상
  CONSTRAINT products_id_slot_uq UNIQUE (id, slot)
);

CREATE TABLE public.moly_life_ments (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  content    text    NOT NULL,
  weather    text    NOT NULL CHECK (weather IN ('sunny','cloudy','rainy','windy')),
  is_active  boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.app_config (
  key         text PRIMARY KEY,
  value       jsonb NOT NULL,
  description text,
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- ─────────────────────────────────────────────────────────────
-- 3. 대화(messages → greetings 순서) · 주문 · 원장 · 일일 통계
-- ─────────────────────────────────────────────────────────────
CREATE TABLE public.messages (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       uuid   NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  sender        text   NOT NULL CHECK (sender IN ('user','moly')),
  kind          text   NOT NULL DEFAULT 'normal' CHECK (kind IN ('normal','greeting')),
  content       text   NOT NULL,
  input_tokens  integer,
  output_tokens integer,
  cache_read_tokens  integer,   -- 프롬프트 캐시 텔레메트리(실원가·히트율)
  cache_write_tokens integer,
  billable_tokens    integer,   -- 원가 가중 청구 스냅샷(가중치 변경 후 재감사)
  activity_date date   NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX messages_user_id_desc_idx  ON public.messages (user_id, id DESC);
CREATE INDEX messages_user_actdate_idx  ON public.messages (user_id, activity_date);

CREATE TABLE public.greetings (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id              uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  context              text NOT NULL CHECK (context IN ('onboarding','home_enter','morning','evening','comeback')),
  content              text NOT NULL,
  activity_date        date NOT NULL,
  committed_message_id bigint REFERENCES public.messages(id) ON DELETE SET NULL,
  created_at           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT greetings_user_ctx_date_uq UNIQUE (user_id, context, activity_date)
);

-- 주문 — 모든 구매의 단일 진입점 (DB_REFACTOR §B.2)
-- currency: KRW = IAP 건초 구매(실결제) / HAY = 상점 꾸미기 구매(재화 차감)
CREATE TABLE public.orders (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid    NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  currency     text    NOT NULL CHECK (currency IN ('KRW','HAY')),
  status       text    NOT NULL CHECK (status IN ('pending','paid','failed','refunded')),
  total_amount integer NOT NULL CHECK (total_amount >= 0),
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX orders_user_created_idx ON public.orders (user_id, created_at DESC);
CREATE TRIGGER orders_set_updated_at BEFORE UPDATE ON public.orders
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.order_items (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id   uuid    NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id uuid    NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
  quantity   integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  unit_price integer NOT NULL CHECK (unit_price >= 0)   -- 구매 시점 가격 스냅샷(가격정책 변동 대비)
);
CREATE INDEX order_items_order_idx   ON public.order_items (order_id);
CREATE INDEX order_items_product_idx ON public.order_items (product_id);

CREATE TABLE public.hay_transactions (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       uuid    NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type          text    NOT NULL CHECK (type IN (
                  'attendance','ad_reward','routine_reward','iap_purchase',
                  'subscription_grant','shop_purchase','refund_revoke','admin_adjustment')),
  amount        integer NOT NULL CHECK (amount <> 0),
  balance_after integer NOT NULL,
  order_id      uuid REFERENCES public.orders(id) ON DELETE SET NULL,  -- 구매 관련 원장만(iap_purchase·shop_purchase)
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX hay_transactions_user_created_idx ON public.hay_transactions (user_id, created_at DESC);
CREATE INDEX hay_transactions_order_idx        ON public.hay_transactions (order_id);

CREATE TABLE public.user_daily_stats (
  id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                   uuid     NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  activity_date             date     NOT NULL,
  tokens_used               integer  NOT NULL DEFAULT 0,
  ad_reward_count           smallint NOT NULL DEFAULT 0,
  attendance_claimed_at     timestamptz,
  routine_reward_claimed_at timestamptz,
  CONSTRAINT user_daily_stats_user_date_uq UNIQUE (user_id, activity_date)
);

-- ─────────────────────────────────────────────────────────────
-- 4. 구독 · 결제 · 증정
-- ─────────────────────────────────────────────────────────────
CREATE TABLE public.subscriptions (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                 uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  plan                    text NOT NULL CHECK (plan IN ('monthly','yearly')),
  status                  text NOT NULL CHECK (status IN ('active','grace_period','expired','revoked')),
  original_transaction_id text NOT NULL UNIQUE,
  latest_transaction_id   text,
  purchased_at            timestamptz,
  expires_at              timestamptz,
  auto_renew_enabled      boolean NOT NULL DEFAULT true,
  environment             text,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX subscriptions_user_idx ON public.subscriptions (user_id);
CREATE TRIGGER subscriptions_set_updated_at BEFORE UPDATE ON public.subscriptions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.subscription_hay_grants (
  id                          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                     uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  plan                        text NOT NULL CHECK (plan IN ('monthly','yearly')),
  hay_transaction_id          bigint REFERENCES public.hay_transactions(id) ON DELETE SET NULL,
  granted_at                  timestamptz NOT NULL DEFAULT now(),
  -- 환불 회수 멱등(회수 완료 표식)
  revoked_at                  timestamptz,
  clawback_hay_transaction_id bigint REFERENCES public.hay_transactions(id) ON DELETE SET NULL,
  CONSTRAINT subscription_hay_grants_user_plan_uq UNIQUE (user_id, plan)
);

-- 실결제(현금) 기록 — IAP 건초 + 구독 결제(구매·갱신) 통합 (DB_REFACTOR §B.3)
-- 매출 집계 = payments 단일 테이블.
CREATE TABLE public.payments (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id              uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  -- CASCADE 사유: order/subscription 삭제는 회원탈퇴 CASCADE 경로뿐 — SET NULL이면 탈퇴 중 target_ck 위반
  order_id             uuid REFERENCES public.orders(id) ON DELETE CASCADE,          -- IAP 건초 주문과 1:1
  subscription_id      uuid REFERENCES public.subscriptions(id) ON DELETE CASCADE,   -- 구독 결제(구매·갱신)
  store                text NOT NULL DEFAULT 'app_store',
  store_transaction_id text NOT NULL UNIQUE,   -- 멱등 키(영수증 중복 지급 방지)
  amount               integer,                -- 결제금액(KRW). 이벤트에 없으면 NULL
  currency             text NOT NULL DEFAULT 'KRW',
  status               text NOT NULL CHECK (status IN ('paid','refunded')),
  paid_at              timestamptz,
  created_at           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT payments_target_ck CHECK (order_id IS NOT NULL OR subscription_id IS NOT NULL)
);
CREATE INDEX payments_user_idx         ON public.payments (user_id);
CREATE INDEX payments_order_idx        ON public.payments (order_id);
CREATE INDEX payments_subscription_idx ON public.payments (subscription_id);

-- ─────────────────────────────────────────────────────────────
-- 5. 인벤토리 + 장착 — user_items (보유 + 장착 상태 통합)
--    equipped_slot NULL = 미장착. theme은 사용자마다 항상 1개 장착한다.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE public.user_items (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  product_id    uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  source        text NOT NULL DEFAULT 'purchase' CHECK (source IN ('purchase','subscription','admin_grant')),
  order_id      uuid REFERENCES public.orders(id) ON DELETE SET NULL,
  equipped_slot text CHECK (equipped_slot IN ('theme','head','neck','body')),
  equipped_at   timestamptz,
  acquired_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_items_user_product_uq UNIQUE (user_id, product_id),
  -- ERD §4.9 승계: 슬롯 일치를 DB가 강제(복합 FK — equipped_slot NULL이면 미평가)
  CONSTRAINT user_items_product_slot_fk
    FOREIGN KEY (product_id, equipped_slot) REFERENCES public.products(id, slot),
  CONSTRAINT user_items_equipped_ck CHECK (equipped_at IS NULL OR equipped_slot IS NOT NULL)
);
CREATE INDEX user_items_user_idx    ON public.user_items (user_id);
CREATE INDEX user_items_product_idx ON public.user_items (product_id);
CREATE INDEX user_items_order_idx   ON public.user_items (order_id);
-- 슬롯당 1개 장착
CREATE UNIQUE INDEX user_items_user_equipped_slot_uq
  ON public.user_items (user_id, equipped_slot) WHERE equipped_slot IS NOT NULL;

-- ─────────────────────────────────────────────────────────────
-- 6. 일기
-- ─────────────────────────────────────────────────────────────
CREATE TABLE public.diaries (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  diary_date     date NOT NULL,
  source         text NOT NULL CHECK (source IN ('llm','preset','welcome')),
  preset_ment_id uuid REFERENCES public.moly_life_ments(id) ON DELETE SET NULL,
  content        text NOT NULL,
  weather        text NOT NULL CHECK (weather IN ('sunny','cloudy','rainy','windy')),
  published_at   timestamptz,
  first_read_at  timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT diaries_user_date_uq UNIQUE (user_id, diary_date)
);
CREATE INDEX diaries_user_published_idx ON public.diaries (user_id, published_at);

-- ─────────────────────────────────────────────────────────────
-- 7. 루틴
-- ─────────────────────────────────────────────────────────────
CREATE TABLE public.routines (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id            uuid     NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  name               text     NOT NULL,
  frequency_per_week smallint NOT NULL,            -- 항상 요일 수(응답 하위호환용)
  days_of_week       smallint[] NOT NULL,          -- 지정 요일(ISO 1=월…7=일)
  reminder_enabled   boolean  NOT NULL DEFAULT false,
  reminder_time      time,
  deleted_at         timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX routines_user_idx ON public.routines (user_id);
CREATE TRIGGER routines_set_updated_at BEFORE UPDATE ON public.routines
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.routine_completions (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  routine_id    uuid NOT NULL REFERENCES public.routines(id) ON DELETE CASCADE,
  user_id       uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  activity_date date NOT NULL,
  completed_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT routine_completions_routine_date_uq UNIQUE (routine_id, activity_date)
);
CREATE INDEX routine_completions_routine_idx ON public.routine_completions (routine_id);
CREATE INDEX routine_completions_user_idx    ON public.routine_completions (user_id);

-- ─────────────────────────────────────────────────────────────
-- 8. 알림 · 디바이스
-- ─────────────────────────────────────────────────────────────
CREATE TABLE public.user_notification_settings (
  user_id uuid    NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type    text    NOT NULL CHECK (type IN ('morning_diary','evening_chat')),
  enabled boolean NOT NULL DEFAULT true,
  PRIMARY KEY (user_id, type)
);

CREATE TABLE public.user_devices (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  platform       text NOT NULL CHECK (platform IN ('ios')),
  push_token     text NOT NULL UNIQUE,
  last_active_at timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX user_devices_user_idx ON public.user_devices (user_id);

-- ─────────────────────────────────────────────────────────────
-- 9. 광고 SSV · 멱등키 (ERD 밖, 백엔드 신규)
-- ─────────────────────────────────────────────────────────────
CREATE TABLE public.reward_ad_sessions (
  session_id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id            uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  activity_date      date NOT NULL,
  ssv_transaction_id text UNIQUE,           -- SSV 도착 시 기록(재전송 멱등)
  granted            boolean NOT NULL DEFAULT false,
  created_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX reward_ad_sessions_user_idx ON public.reward_ad_sessions (user_id);

-- 대화 컨텍스트 상태(앵커 append-only + 기억 스냅샷). 기억 평문 사본 → 민감(RLS + REVOKE 아래).
CREATE TABLE public.chat_contexts (
  user_id             uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  anchor_message_id   bigint NOT NULL DEFAULT 0 CHECK (anchor_message_id >= 0),
  memory_text         text,
  memory_refreshed_at timestamptz,
  updated_at          timestamptz NOT NULL DEFAULT now()
);
REVOKE ALL ON public.chat_contexts FROM anon, authenticated;

CREATE TABLE public.idempotency_keys (
  user_id    uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  key        text NOT NULL,
  response   jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, key)
);

-- ─────────────────────────────────────────────────────────────
-- 10. RLS — deny-default (심층 방어). 서버는 테이블 owner 롤이라 우회.
--     클라 데이터 경로는 전부 서버 API → anon/authenticated 직접 접근 차단.
--     (클라 직접 읽기가 필요해지면 여기에 own-row SELECT 정책 추가)
-- ─────────────────────────────────────────────────────────────
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'profiles','products','moly_life_ments','app_config',
    'messages','greetings','orders','order_items','hay_transactions','user_daily_stats',
    'subscriptions','subscription_hay_grants','payments',
    'user_items','diaries','routines','routine_completions',
    'user_notification_settings','user_devices','reward_ad_sessions','idempotency_keys',
    'chat_contexts'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
  END LOOP;
END $$;

COMMIT;
