-- moly-backend 스키마 (Supabase / PostgreSQL)
-- 단일 소스 = app/models/*.py (코드가 실제로 읽고 쓰는 형태). 설계 근거 = docs/ERD.md.
-- enum은 모델이 String 매핑(asyncpg 바인딩 마찰 회피) → DB도 text + CHECK 제약으로 검증.
-- 클라 직접 쓰기 없음(전부 서버 API 경유) → RLS deny-default(심층 방어). 서버는 owner 롤이라 RLS 우회.
-- 실행: psql "<conn>" -f db/schema.sql  (또는 apply 스크립트)

BEGIN;

-- ─────────────────────────────────────────────────────────────
-- 0. 레거시(옛 프로젝트) 테이블 폐기 — 사용자 승인(2026-07-08)
-- ─────────────────────────────────────────────────────────────
DROP TABLE IF EXISTS public.messages       CASCADE;
DROP TABLE IF EXISTS public.conversations  CASCADE;
DROP TABLE IF EXISTS public.profiles       CASCADE;

-- updated_at 자동 갱신 트리거 함수(기존 존재 시 재사용). 없으면 생성.
CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ─────────────────────────────────────────────────────────────
-- 1. 계정·프로필
-- ─────────────────────────────────────────────────────────────
CREATE TABLE public.profiles (
  id                 uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  nickname           text        CHECK (char_length(nickname) <= 10),
  language           text        NOT NULL DEFAULT 'ko',
  timezone           text        NOT NULL DEFAULT 'Asia/Seoul',
  hay_balance        integer     NOT NULL DEFAULT 0 CHECK (hay_balance >= 0),
  trial_ends_at      timestamptz,
  review_prompted_at timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER profiles_set_updated_at BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ─────────────────────────────────────────────────────────────
-- 2. 서버 원본 카탈로그(FK 없음) — hay_packs / shop_items / moly_life_ments / app_config
-- ─────────────────────────────────────────────────────────────
CREATE TABLE public.hay_packs (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  app_store_product_id text    NOT NULL UNIQUE,
  hay_amount           integer NOT NULL,
  price_krw            integer,
  is_active            boolean NOT NULL DEFAULT true,
  sort_order           integer NOT NULL DEFAULT 0
);

CREATE TABLE public.shop_items (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slot               text    NOT NULL CHECK (slot IN ('background','head','neck','body')),
  name               text    NOT NULL,
  description        text,
  price_hay          integer,
  is_subscriber_only boolean NOT NULL DEFAULT false,
  assets             jsonb   NOT NULL,
  is_active          boolean NOT NULL DEFAULT true,
  sort_order         integer NOT NULL DEFAULT 0,
  -- ERD §4.7: 구독 전용 ↔ 비매품(price NULL) 상호 강제
  CONSTRAINT shop_items_subonly_ck CHECK (is_subscriber_only = (price_hay IS NULL)),
  -- user_equipment 복합 FK (shop_item_id, slot) → (id, slot) 대상
  CONSTRAINT shop_items_id_slot_uq UNIQUE (id, slot)
);

CREATE TABLE public.moly_life_ments (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  content    text    NOT NULL,
  weather    text    NOT NULL CHECK (weather IN ('sunny','cloudy','rainy','windy')),
  is_active  boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.app_config (
  key         text PRIMARY KEY,
  value       jsonb NOT NULL,
  description text,
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- ─────────────────────────────────────────────────────────────
-- 3. 대화(messages → greetings 순서) · 원장 · 일일 통계
-- ─────────────────────────────────────────────────────────────
CREATE TABLE public.messages (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       uuid   NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  sender        text   NOT NULL CHECK (sender IN ('user','moly')),
  kind          text   NOT NULL DEFAULT 'normal' CHECK (kind IN ('normal','greeting')),
  content       text   NOT NULL,
  input_tokens  integer,
  output_tokens integer,
  activity_date date   NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX messages_user_id_desc_idx  ON public.messages (user_id, id DESC);
CREATE INDEX messages_user_actdate_idx  ON public.messages (user_id, activity_date);

CREATE TABLE public.greetings (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id              uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  context              text NOT NULL CHECK (context IN ('onboarding','home_enter','morning','evening','comeback')),
  content              text NOT NULL,
  activity_date        date NOT NULL,
  committed_message_id bigint REFERENCES public.messages(id) ON DELETE SET NULL,
  created_at           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT greetings_user_ctx_date_uq UNIQUE (user_id, context, activity_date)
);

CREATE TABLE public.hay_transactions (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       uuid    NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type          text    NOT NULL CHECK (type IN (
                  'attendance','ad_reward','routine_reward','iap_purchase',
                  'subscription_grant','shop_purchase','refund_revoke','admin_adjustment')),
  amount        integer NOT NULL CHECK (amount <> 0),
  balance_after integer NOT NULL,
  ref_id        text,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX hay_transactions_user_created_idx ON public.hay_transactions (user_id, created_at DESC);

CREATE TABLE public.user_daily_stats (
  id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                   uuid     NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  activity_date             date     NOT NULL,
  tokens_used               integer  NOT NULL DEFAULT 0,
  ad_reward_count           smallint NOT NULL DEFAULT 0,
  attendance_claimed_at     timestamptz,
  routine_reward_claimed_at timestamptz,
  CONSTRAINT user_daily_stats_user_date_uq UNIQUE (user_id, activity_date)
);

-- ─────────────────────────────────────────────────────────────
-- 4. 구독 · IAP · 증정
-- ─────────────────────────────────────────────────────────────
CREATE TABLE public.subscriptions (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                 uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  plan                    text NOT NULL CHECK (plan IN ('monthly','yearly')),
  status                  text NOT NULL CHECK (status IN ('active','grace_period','expired','revoked')),
  original_transaction_id text NOT NULL UNIQUE,
  latest_transaction_id   text,
  purchased_at            timestamptz,
  expires_at              timestamptz,
  auto_renew_enabled      boolean NOT NULL DEFAULT true,
  environment             text,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX subscriptions_user_idx ON public.subscriptions (user_id);
CREATE TRIGGER subscriptions_set_updated_at BEFORE UPDATE ON public.subscriptions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.subscription_hay_grants (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id            uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  plan               text NOT NULL CHECK (plan IN ('monthly','yearly')),
  hay_transaction_id bigint REFERENCES public.hay_transactions(id) ON DELETE SET NULL,
  granted_at         timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT subscription_hay_grants_user_plan_uq UNIQUE (user_id, plan)
);

CREATE TABLE public.iap_purchases (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id            uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  hay_pack_id        uuid REFERENCES public.hay_packs(id) ON DELETE SET NULL,
  transaction_id     text NOT NULL UNIQUE,
  status             text NOT NULL CHECK (status IN ('pending','verified','failed','refunded')),
  hay_transaction_id bigint REFERENCES public.hay_transactions(id) ON DELETE SET NULL,
  purchased_at       timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX iap_purchases_user_idx ON public.iap_purchases (user_id);

-- ─────────────────────────────────────────────────────────────
-- 5. 인벤토리 · 장착
-- ─────────────────────────────────────────────────────────────
CREATE TABLE public.user_items (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id            uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  shop_item_id       uuid NOT NULL REFERENCES public.shop_items(id) ON DELETE CASCADE,
  hay_transaction_id bigint REFERENCES public.hay_transactions(id) ON DELETE SET NULL,
  acquired_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_items_user_item_uq UNIQUE (user_id, shop_item_id)
);
CREATE INDEX user_items_user_idx ON public.user_items (user_id);

CREATE TABLE public.user_equipment (
  user_id      uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  slot         text NOT NULL CHECK (slot IN ('background','head','neck','body')),
  shop_item_id uuid NOT NULL,
  equipped_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, slot),
  -- ERD §4.9: 슬롯 일치를 DB가 강제(복합 FK)
  CONSTRAINT user_equipment_item_slot_fk
    FOREIGN KEY (shop_item_id, slot) REFERENCES public.shop_items(id, slot) ON DELETE CASCADE
);

-- ─────────────────────────────────────────────────────────────
-- 6. 일기
-- ─────────────────────────────────────────────────────────────
CREATE TABLE public.diaries (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  diary_date     date NOT NULL,
  source         text NOT NULL CHECK (source IN ('llm','preset')),
  preset_ment_id uuid REFERENCES public.moly_life_ments(id) ON DELETE SET NULL,
  content        text NOT NULL,
  weather        text NOT NULL CHECK (weather IN ('sunny','cloudy','rainy','windy')),
  published_at   timestamptz,
  first_read_at  timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT diaries_user_date_uq UNIQUE (user_id, diary_date)
);
CREATE INDEX diaries_user_published_idx ON public.diaries (user_id, published_at);

-- ─────────────────────────────────────────────────────────────
-- 7. 루틴
-- ─────────────────────────────────────────────────────────────
CREATE TABLE public.routines (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id            uuid     NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  name               text     NOT NULL,
  frequency_per_week smallint NOT NULL,            -- 목표 횟수(요일별이면 요일 수)
  days_of_week       smallint[],                   -- 요일별(ISO 1=월…7=일). null=주 N회 모드
  reminder_enabled   boolean  NOT NULL DEFAULT false,
  reminder_time      time,
  deleted_at         timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX routines_user_idx ON public.routines (user_id);
CREATE TRIGGER routines_set_updated_at BEFORE UPDATE ON public.routines
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.routine_completions (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  routine_id    uuid NOT NULL REFERENCES public.routines(id) ON DELETE CASCADE,
  user_id       uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  activity_date date NOT NULL,
  completed_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT routine_completions_routine_date_uq UNIQUE (routine_id, activity_date)
);
CREATE INDEX routine_completions_routine_idx ON public.routine_completions (routine_id);
CREATE INDEX routine_completions_user_idx    ON public.routine_completions (user_id);

-- ─────────────────────────────────────────────────────────────
-- 8. 알림 · 디바이스
-- ─────────────────────────────────────────────────────────────
CREATE TABLE public.user_notification_settings (
  user_id uuid    NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type    text    NOT NULL CHECK (type IN ('morning_diary','evening_chat')),
  enabled boolean NOT NULL DEFAULT true,
  PRIMARY KEY (user_id, type)
);

CREATE TABLE public.user_devices (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  platform       text NOT NULL CHECK (platform IN ('ios')),
  push_token     text NOT NULL UNIQUE,
  last_active_at timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX user_devices_user_idx ON public.user_devices (user_id);

-- ─────────────────────────────────────────────────────────────
-- 9. 광고 SSV · 멱등키 (ERD 밖, 백엔드 신규)
-- ─────────────────────────────────────────────────────────────
CREATE TABLE public.ad_rewards (
  ssv_transaction_id text PRIMARY KEY,
  user_id            uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  activity_date      date NOT NULL,
  granted            boolean NOT NULL DEFAULT false,
  created_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ad_rewards_user_idx ON public.ad_rewards (user_id);

CREATE TABLE public.idempotency_keys (
  user_id    uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  key        text NOT NULL,
  response   jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, key)
);

-- ─────────────────────────────────────────────────────────────
-- 10. RLS — deny-default (심층 방어). 서버는 테이블 owner 롤이라 우회.
--     클라 데이터 경로는 전부 서버 API → anon/authenticated 직접 접근 차단.
--     (클라 직접 읽기가 필요해지면 여기에 own-row SELECT 정책 추가)
-- ─────────────────────────────────────────────────────────────
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'profiles','hay_packs','shop_items','moly_life_ments','app_config',
    'messages','greetings','hay_transactions','user_daily_stats',
    'subscriptions','subscription_hay_grants','iap_purchases',
    'user_items','user_equipment','diaries','routines','routine_completions',
    'user_notification_settings','user_devices','ad_rewards','idempotency_keys'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
  END LOOP;
END $$;

COMMIT;
