"""Build v8 server copy from reviewed editorial paragraphs, without importing the app.

All coverage, provenance and review checks complete before any output is replaced.
Run --check to compare generated bytes without writing. A failed review never
falls back to legacy prose or partially translated assets.
"""
from __future__ import annotations

import argparse
from copy import deepcopy
from hashlib import sha256
import json
from pathlib import Path
import re
import tempfile
import unicodedata

ROOT = Path(__file__).resolve().parents[1]
VERSION = "fortune-copy.v8-localized.2"
FIRST_VISIT_IDENTITY_HASH = "e588974413014dad1c44c07c297043af28dcccbbe41b8eba15b548aa68117bed"
MAJORS = ("fool", "magician", "high_priestess", "empress", "emperor", "hierophant", "lovers",
          "chariot", "strength", "hermit", "wheel_of_fortune", "justice", "hanged_man", "death",
          "temperance", "devil", "tower", "star", "moon", "sun", "judgement", "world")
LOCALES = ("ko", "en", "ja")
AXES = ("overall", "love", "money", "work", "energy")
FILES = dict(zip(LOCALES, ("copy.v3.json", "copy.v3.en.json", "copy.v3.ja.json")))
PARAGRAPH_COUNTS = {"overall": {2}, "love": {3}, "money": {1, 2}, "work": {2}, "energy": {1, 2}}


def digest(value) -> str:
    return sha256(json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


def _pairs(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def read_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=_pairs)


def encode(value) -> bytes:
    return (json.dumps(value, ensure_ascii=False, indent=2) + "\n").encode()


def validate_bundle(key: str, bundle: dict, locale: str):
    axis = key.split(".", 1)[0]
    fields = {"paragraphs", "headline", "do", "pause"} if axis == "overall" else {"paragraphs"}
    if not isinstance(bundle, dict) or set(bundle) != fields:
        raise ValueError(f"{locale}/{key}: invalid editorial fields")
    paragraphs = bundle["paragraphs"]
    if not isinstance(paragraphs, list) or len(paragraphs) not in PARAGRAPH_COUNTS[axis]:
        raise ValueError(f"{locale}/{key}: invalid paragraph count")
    values = [*paragraphs, *(bundle[f] for f in ("headline", "do", "pause") if f in bundle)]
    for text in values:
        if not isinstance(text, str) or not text or text != text.strip() or unicodedata.normalize("NFC", text) != text:
            raise ValueError(f"{locale}/{key}: invalid text")
        if any(c in text for c in ("\n", "\r")) or re.search(r"TODO|TBD|\{\{|\}\}|\.\.\.", text, re.I):
            raise ValueError(f"{locale}/{key}: placeholder or forced newline")
        if re.search(r"타로|タロット|\btarot\b|major\.[a-z_]+|(?:cups|swords|wands|pentacles)\.\d", text, re.I):
            raise ValueError(f"{locale}/{key}: internal card metadata")
        if locale != "ko" and re.search(r"[가-힣]", text):
            raise ValueError(f"{locale}/{key}: untranslated Korean")
        if locale == "en" and re.search(r"[\u3040-\u30ff\u3400-\u9fff]", text):
            raise ValueError(f"{locale}/{key}: non-English script")
    if any(not text.endswith((".", "!", "?", "。", "！", "？")) for text in paragraphs):
        raise ValueError(f"{locale}/{key}: incomplete paragraph")


def to_wire(key: str, bundle: dict) -> dict:
    if key.startswith("overall."):
        return {"headline": bundle["headline"], "flow": list(bundle["paragraphs"]),
                "do": bundle["do"], "pause": bundle["pause"]}
    return {"text": list(bundle["paragraphs"])}


def build_outputs(root: Path = ROOT) -> dict[Path, bytes]:
    resource = root / "app/resources/fortune"
    ko_dir = root / "docs/fortune-content/ko-rewrite"
    localized = root / "docs/fortune-content/localization"
    meaning_sources = read_json(ko_dir / "source-briefs.json")
    keys = set(meaning_sources)
    cards = {f"major.{name}" for name in MAJORS} | {f"{suit}.{rank:02d}" for suit in ("cups", "swords", "wands", "pentacles") for rank in range(1, 15)}
    expected_keys = {f"{axis}.{card}.{orientation}" for axis in AXES for card in cards for orientation in ("upright", "reversed")}
    if keys != expected_keys:
        raise ValueError("source meaning coverage must be 156 per axis")
    editorial = {}
    briefs = {}
    for locale in LOCALES:
        source_dir = ko_dir if locale == "ko" else localized / locale
        editorial[locale] = {}
        for axis in AXES:
            values = read_json(source_dir / f"{axis}.json")
            expected = {k for k in keys if k.startswith(axis + ".")}
            if not isinstance(values, dict) or set(values) != expected:
                raise ValueError(f"{locale}/{axis}: incomplete editorial coverage")
            for key, bundle in values.items():
                validate_bundle(key, bundle, locale)
                if locale != "ko" and len(bundle["paragraphs"]) != len(editorial["ko"][key]["paragraphs"]):
                    raise ValueError(f"{locale}/{key}: paragraph parity mismatch")
            editorial[locale].update(values)
            if locale == "ko":
                axis_briefs = read_json(ko_dir / f"{axis}.briefs.json")
                if set(axis_briefs) != expected:
                    raise ValueError(f"{axis}: incomplete brief coverage")
                briefs.update(axis_briefs)
    ko_review = read_json(ko_dir / "review.json")
    if ko_review.get("status") != "complete":
        raise ValueError("Korean independent review is incomplete")
    review = read_json(localized / "review.json")
    if (review.get("schema") != "moly-fortune-localization-review-v1"
            or review.get("status") != "complete" or review.get("copy_version") != VERSION
            or review.get("reviewer") != "root" or review.get("human_review") is not False
            or set(review.get("locales", {})) != {"en", "ja"}):
        raise ValueError("localized independent review is incomplete")
    if not isinstance(review.get("findings"), list) or any(not isinstance(item, dict) or item.get("status") == "open" for item in review["findings"]):
        raise ValueError("independent review has open findings")
    for key, bundle in editorial["ko"].items():
        original = ko_review["axes"][key.split(".", 1)[0]].get(key, {})
        if original.get("status") != "pass" or original.get("read_bundle_sha256") != digest(bundle):
            raise ValueError(f"{key}: stale Korean independent review")
    dimensions = {"naturalness", "readability", "axis_specificity", "meaning_parity", "calibrated_confidence"}
    for locale in ("en", "ja"):
        if set(review["locales"][locale]) != keys:
            raise ValueError(f"{locale}: incomplete independent review coverage")
        for key, bundle in editorial[locale].items():
            proof = review["locales"][locale][key]
            scores = proof.get("scores", {})
            if (proof.get("status") != "pass" or proof.get("read_bundle_sha256") != digest(bundle)
                    or proof.get("source_ko_sha256") != digest(editorial["ko"][key])
                    or set(scores) != dimensions
                    or any(type(value) not in (int, float) or not 4 <= value <= 5 for value in scores.values())):
                raise ValueError(f"{locale}/{key}: stale or failed independent review")
        author = read_json(localized / locale / "author-review.json")
        expected = {key: digest(bundle) for key, bundle in editorial[locale].items()}
        if (author.get("status") != "complete" or author.get("read_bundle_sha256") != expected
                or author.get("actual_self_read_count") != 780):
            raise ValueError(f"{locale}: incomplete or stale author review")
    outputs = {}
    copies = {}
    for locale in LOCALES:
        colors = read_json(resource / {"ko": "copy.v2.json", "en": "copy.v2.en.json", "ja": "copy.v2.ja.json"}[locale])["colors"]
        copies[locale] = {"schema": "fortune-copy-v3", "copy_version": VERSION,
                          "content_status": "agent_reviewed", "locales": [locale],
                          "readings": {key: to_wire(key, editorial[locale][key]) for key in sorted(keys)},
                          "colors": colors}
        outputs[resource / FILES[locale]] = encode(copies[locale])
    provenance = {"schema": "fortune-tarot-editorial-v2", "copy_version": VERSION,
                  "source": "https://sacred-texts.com/tarot/pkt/index.htm",
                  "policy": "independent-card-draw-complete-paragraphs", "readings": {}}
    for key in sorted(keys):
        brief = briefs[key]
        if f"{key.split('.', 1)[0]}.{brief['card_id']}.{brief['orientation']}" != key:
            raise ValueError(f"{key}: mismatched brief identity")
        if not isinstance(brief["keywords"], list) or not brief["keywords"] or not all(isinstance(word, str) and word.strip() == word and word for word in brief["keywords"]):
            raise ValueError(f"{key}: invalid brief keywords")
        words = list(dict.fromkeys(brief["keywords"]))[:3]
        if len(words) < 2:
            words.append(brief["fortune_judgment"])
        provenance["readings"][key] = {
            "card_id": brief["card_id"], "orientation": brief["orientation"], "axis": key.split(".", 1)[0],
            "meaning": ", ".join(brief["keywords"]), "angle": brief["fortune_judgment"],
            "observations": words,
            "copy_sha256": {locale: digest(copies[locale]["readings"][key]) for locale in LOCALES},
        }
    outputs[resource / "tarot-editorial.v2.json"] = encode(provenance)
    first = deepcopy(read_json(resource / "first-visit.v1.json"))
    identity = [{"id": entry["id"], "cards": entry["cards"]} for entry in first["sets"]]
    if digest(identity) != FIRST_VISIT_IDENTITY_HASH:
        raise ValueError("first visit identities differ from the approved six sets")
    if len(first["sets"]) != 6:
        raise ValueError("first visit requires the existing six sets")
    for entry in first["sets"]:
        if set(entry["cards"]) != set(AXES):
            raise ValueError("invalid first visit card axes")
        entry["copy_by_locale"] = {}
        for locale in LOCALES:
            selected = {axis: copies[locale]["readings"][f"{axis}.{card['card_id']}.{card['orientation']}"]
                        for axis, card in entry["cards"].items()}
            entry["copy_by_locale"][locale] = {"overall": selected["overall"],
                                              "categories": {axis: selected[axis] for axis in AXES[1:]}}
    outputs[resource / "first-visit.v1.json"] = encode(first)
    manifest = read_json(resource / "manifest.v2.json")
    expected_assets = {"rules.v2.json", "copy.v2.json", "copy.v2.en.json", "copy.v2.ja.json",
                       *FILES.values(), "tarot-editorial.v2.json", "first-visit.v1.json"}
    if manifest.get("schema") != "fortune-manifest-v2" or set(manifest.get("assets", {})) != expected_assets:
        raise ValueError("invalid manifest coverage")
    for name in sorted(expected_assets):
        path = resource / name
        raw = outputs[path] if path in outputs else path.read_bytes()
        if path not in outputs and manifest["assets"][name] != {"sha256": sha256(raw).hexdigest()}:
            raise ValueError(f"{name}: unchanged legacy/rule asset hash differs")
        manifest["assets"][name] = {"sha256": sha256(raw).hexdigest()}
    outputs[resource / "manifest.v2.json"] = encode(manifest)
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        outputs = build_outputs()
    except (ValueError, KeyError, TypeError, OSError) as exc:
        print(f"Localized generation blocked before writing: {exc}")
        return 2
    stale = [str(path.relative_to(ROOT)) for path, raw in outputs.items() if not path.exists() or path.read_bytes() != raw]
    if args.check:
        if stale:
            print("Stale localized assets:\n" + "\n".join(stale))
            return 1
    else:
        # Stage every file before replacement; manifest is committed last, so a
        # concurrent reader rejects any interrupted mixed generation by hash.
        with tempfile.TemporaryDirectory(dir=ROOT / "app/resources/fortune") as temp:
            staged = []
            for index, (path, raw) in enumerate(outputs.items()):
                stage = Path(temp) / str(index)
                stage.write_bytes(raw)
                staged.append((stage, path))
            for stage, path in staged:
                stage.replace(path)
    print(f"Localized assets {'checked' if args.check else 'written'}: {len(outputs)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
